import com.fiskentra.app.model.*;
import java.time.*;
import java.util.*;
public final class MapPoliciesTest {
    private static int checks;
    private static void check(boolean value,String message){checks++;if(!value)throw new AssertionError(message);}
    public static void main(String[] args){
        MapCameraPolicy camera=new MapCameraPolicy();check(camera.mode()==MapCameraPolicy.Mode.FREE,"free initial");camera.locate(false);check(camera.mode()==MapCameraPolicy.Mode.FOLLOW_POSITION,"locate position");camera.locate(false);check(camera.mode()==MapCameraPolicy.Mode.FOLLOW_POSITION,"unknown direction cannot rotate");camera.locate(true);check(camera.mode()==MapCameraPolicy.Mode.FOLLOW_HEADING,"second locate heading");camera.gesture();camera.orientation(5,90,0,true);check(camera.mode()==MapCameraPolicy.Mode.FREE,"GPS after gesture stays free");camera.north();check(camera.mode()==MapCameraPolicy.Mode.FREE,"north keeps free");camera.locate(true);camera.locate(true);camera.north();check(camera.mode()==MapCameraPolicy.Mode.FOLLOW_POSITION,"north leaves heading");camera.restore("bad legacy state");check(camera.mode()==MapCameraPolicy.Mode.FREE,"unknown state safe");
        camera=new MapCameraPolicy();check(camera.orientation(0,200,359,true)==359,"sensor used at rest");check(Math.abs(MapCameraPolicy.delta(359,1)-2)<.001,"north wrap shortest arc");check(camera.orientation(0,200,1,true)==359,"deadband at north");check(camera.orientation(0,200,20,true)<20,"angle smoothed across north");camera=new MapCameraPolicy();check(Double.isNaN(camera.orientation(0,180,20,false)),"poor sensor no random bearing");check(camera.orientation(2,90,0,true)==90,"course at walking threshold");double kept=camera.orientation(1.4,90,270,true);check(kept==90,"hysteresis keeps stable course");check(camera.orientation(1,90,270,true)!=90,"slow speed uses sensor");
        camera=new MapCameraPolicy();camera.orientation(0,Double.NaN,90,true,1000,1000);camera.locate(camera.orientationAvailable());camera.locate(camera.orientationAvailable());check(camera.mode()==MapCameraPolicy.Mode.FOLLOW_HEADING,"fresh sensor enables heading follow");
        double held=camera.orientation(0,Double.NaN,90,true,1000,4001);check(held==90&&!camera.orientationAvailable(),"expired sensor preserves stable angle without advertising live orientation");check(camera.mode()==MapCameraPolicy.Mode.FOLLOW_POSITION,"heading loss degrades to position follow");camera.locate(camera.orientationAvailable());check(camera.mode()==MapCameraPolicy.Mode.FOLLOW_POSITION,"locate cannot reenter heading with expired source");
        camera.orientation(0,Double.NaN,180,true,4500,4500);check(camera.orientationAvailable(),"fresh sensor restores availability");camera.orientation(0,Double.NaN,180,false,4500,4501);check(!camera.orientationAvailable(),"unreliable current sample invalidates orientation");camera.orientation(2,270,90,true,1000,5000);check(camera.orientationAvailable(),"fresh motion course survives stale sensor");camera.orientation(0,Double.NaN,90,true,1000,5001);check(!camera.orientationAvailable(),"stop cannot reuse expired sensor or course");check(!MapCameraPolicy.sensorFresh(6000,5000)&&!MapCameraPolicy.sensorFresh(0,5000),"future and missing sensor timestamps rejected");
        long now=40_000_000_000L;check(LocationQualityPolicy.fresh(now-29_000_000_000L,now),"29 seconds fresh");check(!LocationQualityPolicy.fresh(now-31_000_000_000L,now),"31 seconds stale");check(!LocationQualityPolicy.fresh(now,1),"reboot monotonic origin rejected");check(!LocationQualityPolicy.fresh(0,now),"unknown clock not fresh");check(LocationQualityPolicy.track(now,now,75),"75m track allowed");check(!LocationQualityPolicy.guidance(now,now,75),"75m guidance rejected");check(LocationQualityPolicy.guidance(now,now,50),"50m guidance allowed");check(!LocationQualityPolicy.arrival(now,now,50),"50m arrival rejected");check(LocationQualityPolicy.arrival(now,now,25),"25m arrival allowed");check(!LocationQualityPolicy.accuracy(Double.NaN),"unknown accuracy no halo");check(!LocationQualityPolicy.accuracy(0),"zero accuracy no fake halo");
        for(double lat:new double[]{0,52,80})for(double meters:new double[]{10,50,150}){double[] edge=LocationQualityPolicy.offset(lat,24,meters,90);check(Math.abs(FieldNavigation.distance(lat,24,edge[0],edge[1])-meters)<.1,"metric accuracy geometry latitude "+lat+" radius "+meters);}
        check(LocationQualityPolicy.state(false,true,true,now,now)==LocationQualityPolicy.State.PERMISSION_REQUIRED,"permission distinct");check(LocationQualityPolicy.state(true,false,true,now,now)==LocationQualityPolicy.State.LOCATION_DISABLED,"disabled distinct");
        long[] dst=MapFilterPolicy.dates(LocalDate.of(2026,3,29),LocalDate.of(2026,3,29),ZoneId.of("Europe/Berlin"));check(dst[1]-dst[0]==23*3600000L,"DST start local day 23h");long[] fall=MapFilterPolicy.dates(LocalDate.of(2026,10,25),LocalDate.of(2026,10,25),ZoneId.of("Europe/Berlin"));check(fall[1]-fall[0]==25*3600000L,"DST end local day 25h");
        SavedPoint first=new SavedPoint(1,52,24,dst[0],"Catch","").withTripId(100).withFavorite(true);SavedPoint second=new SavedPoint(2,52,24,dst[0]+1,"Camp","").withTripId(101);SavedPoint unknown=new SavedPoint(3,52,24,dst[1],"Legacy unknown","");SavedPoint pending=new SavedPoint(4,Double.NaN,Double.NaN,dst[0],"Catch","").withTripId(100);
        MapFilterPolicy f=new MapFilterPolicy("current","",0,Long.MAX_VALUE,Arrays.asList("Catch","Camp"),false);check(f.matches(first,"100")&&!f.matches(second,"100"),"two trips same day separated");check(f.matches(pending,"100"),"no location records counted by same predicate");check(!f.matches(first,"0"),"no active trip not all history");f=new MapFilterPolicy("all","",0,Long.MAX_VALUE,Arrays.asList("Catch","Camp"),false);check(f.matches(first,"0")&&f.matches(second,"0"),"types OR");f=new MapFilterPolicy("all","",0,Long.MAX_VALUE,Arrays.asList("Catch","Camp"),true);check(f.matches(first,"0")&&!f.matches(second,"0"),"favorite AND");f=new MapFilterPolicy("all","",0,Long.MAX_VALUE,Collections.emptyList(),false);check(f.apply(Arrays.asList(first,second),"0").isEmpty(),"no types explicitly empty");f=new MapFilterPolicy("dates","",dst[0],dst[1],Arrays.asList(MapFilterPolicy.TYPES),false);check(f.matches(first,"0")&&!f.matches(unknown,"0"),"dates half open");check(MapFilterPolicy.all().matches(unknown,"0"),"unknown legacy types visible in all");
        List<FishingDay> sessions=Arrays.asList(new FishingDay(10,101,200),new FishingDay(20,200,300),new FishingDay(30,99,100));
        SavedPoint owned=new SavedPoint(10,52,24,150,"Catch","").withTripId(10);
        SavedPoint moved=owned.withTripId(20);
        SavedPoint assignedOutsideTime=new SavedPoint(11,52,24,80,"Catch","").withTripId(10);
        SavedPoint noFix=new SavedPoint(12,Double.NaN,Double.NaN,150,"Catch","").withTripId(10);
        SavedPoint earlyFlic=new SavedPoint(13,52,24,100,"Waypoint","").withTripId(100);
        List<SavedPoint> events=TripEventPolicy.forTrack(Arrays.asList(owned,moved,assignedOutsideTime,noFix,earlyFlic,owned.withTripId(0),owned.withTripId(30)),sessions,100,200);
        check(events.size()==4,"events use session IDs, exclude reassigned, unassigned and adjacent sessions");
        check(events.contains(assignedOutsideTime),"manual assignment takes priority over capture time");
        check(events.contains(noFix),"trip events retain captures without GPS");
        check(events.contains(earlyFlic),"recording ID before fishing day creation remains included");
        check(!events.contains(moved),"move to another trip immediately removes event from summary");
        check(TripEventPolicy.forTrack(Arrays.asList(owned),sessions,0,200).isEmpty(),"no recording has no events");
        check(TripEventPolicy.forTrack(Arrays.asList(owned),sessions,200,100).isEmpty(),"invalid interval does not expose history");
        check(TripEventPolicy.forTrack(Arrays.asList(owned),Arrays.asList(new FishingDay(10,101,0)),100,Long.MAX_VALUE).size()==1,"active sessions included");
        boolean immutable=false;try{events.clear();}catch(UnsupportedOperationException expected){immutable=true;}check(immutable,"event snapshot immutable");
        System.out.println("PASS "+checks+" map camera/GPS/filter/trip checks");
    }
}
